packages:
  - 'packages/mindapp'
  - 'packages/mind-machine'
  - 'apps/showroom'

allowBuilds:
  '@parcel/watcher': true
  esbuild: true

nodeLinker: hoisted

minimumReleaseAge: 300

minimumReleaseAgeExclude:
  - '@bemedev/*'
  - '@oxlint/binding-linux-riscv64-gnu@1.84.0'
