/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MindmapDemoRouteImport } from './routes/mindmap-demo'
import { Route as CountingRouteImport } from './routes/counting'
import { Route as IndexRouteImport } from './routes/index'

const MindmapDemoRoute = MindmapDemoRouteImport.update({
  id: '/mindmap-demo',
  path: '/mindmap-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const CountingRoute = CountingRouteImport.update({
  id: '/counting',
  path: '/counting',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/counting': typeof CountingRoute
  '/mindmap-demo': typeof MindmapDemoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/counting': typeof CountingRoute
  '/mindmap-demo': typeof MindmapDemoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/counting': typeof CountingRoute
  '/mindmap-demo': typeof MindmapDemoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/counting' | '/mindmap-demo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/counting' | '/mindmap-demo'
  id: '__root__' | '/' | '/counting' | '/mindmap-demo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CountingRoute: typeof CountingRoute
  MindmapDemoRoute: typeof MindmapDemoRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/mindmap-demo': {
      id: '/mindmap-demo'
      path: '/mindmap-demo'
      fullPath: '/mindmap-demo'
      preLoaderRoute: typeof MindmapDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counting': {
      id: '/counting'
      path: '/counting'
      fullPath: '/counting'
      preLoaderRoute: typeof CountingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CountingRoute: CountingRoute,
  MindmapDemoRoute: MindmapDemoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
